# Generated by Django 5.0.4 on 2024-05-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_ganre_book_ganres'),
        ('events', '0002_alter_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='books',
        ),
        migrations.CreateModel(
            name='EventBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
