# Generated by Django 5.0.4 on 2024-05-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_related_depositiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='related_depositiry',
            new_name='related_depository',
        ),
    ]
