# Generated by Django 5.0.4 on 2024-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_related_depositiry_event_related_depository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='related_depository',
        ),
        migrations.AddField(
            model_name='eventdepository',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
