# Generated by Django 5.0.4 on 2024-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_related_depository_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdepository',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('DP', 'Departure'), ('AR', 'Arrival')], max_length=2),
        ),
    ]
