# Generated by Django 5.0.4 on 2024-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_related_depository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('DP', 'Departure'), ('AR', 'Arrival'), ('TO', 'Transfer to Depository'), ('TF', 'Transfer from Depository')], max_length=2),
        ),
    ]
