# Generated by Django 5.0.4 on 2024-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('DP', 'Departure'), ('AR', 'Arrival'), ('TO', 'Transfer to Depository'), ('TF', 'Transfer from Depository')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
