# Generated by Django 5.0.4 on 2024-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_event_type_alter_event_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('DP', 'Departure'), ('AR', 'Arrival'), ('TO', 'Transfer from this to Another'), ('TF', 'Transfer to this From Anothet')], db_index=True, max_length=2),
        ),
    ]
