# Generated by Django 5.0.4 on 2024-04-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-first_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
