# Generated by Django 5.0.4 on 2024-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
    ]
