# Generated by Django 5.0.4 on 2024-04-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
    ]
