# Generated by Django 5.0.4 on 2024-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0004_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
