# Generated by Django 5.0.4 on 2024-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
