# Generated by Django 5.0.4 on 2024-04-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depository',
            options={'ordering': ['-name'], 'verbose_name': 'Depository', 'verbose_name_plural': 'Depositories'},
        ),
    ]
