# Generated by Django 5.0.4 on 2024-04-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositories', '0002_alter_depository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depository',
            name='name',
            field=models.CharField(db_index=True, max_length=55),
        ),
    ]
