# Generated by Django 5.0.4 on 2024-05-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositories', '0003_alter_depository_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depository',
            old_name='capacity',
            new_name='books_quantity',
        ),
        migrations.RemoveField(
            model_name='depository',
            name='current_capacity',
        ),
    ]
