# Generated by Django 5.0.4 on 2024-04-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('isbn', models.CharField(max_length=13)),
                ('publication_date', models.DateField()),
                ('price', models.FloatField()),
                ('cover', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('author_id', models.ManyToManyField(to='authors.author')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.publisher')),
            ],
        ),
    ]
