# Generated by Django 5.0.4 on 2024-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_page_count_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=55),
        ),
    ]
