# Generated by Django 5.0.4 on 2024-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default_book_image.jpg', null=True, upload_to=''),
        ),
    ]
