# Generated by Django 5.0.4 on 2024-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Ganre',
                'verbose_name_plural': 'Ganres',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='ganres',
            field=models.ManyToManyField(to='books.ganre'),
        ),
    ]
