# Generated by Django 5.0.4 on 2024-11-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_ganre_book_ganres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
